name: OAuth2 Mock image build & push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: europe-central2-docker.pkg.dev/sap-se-cx-kyma-goat/networking-dev-tools/oauth2-mock/dev
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: europe-central2-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.DOCKER_PUSH_SA_KEY }}
      - name: Build amd64 Docker image
        shell: bash
        run: |
          docker buildx build --platform linux/amd64 --push \
          -t ${{ env.REGISTRY_URL }}:${{ github.sha }}-amd64 -t ${{ env.REGISTRY_URL }}:amd64 --file oauth2-mock/Dockerfile oauth2-mock
      - name: Build arm64 Docker image
        shell: bash
        run: |
          docker buildx build --platform linux/arm64 --push \
          -t ${{ env.REGISTRY_URL }}:${{ github.sha }}-arm64 -t ${{ env.REGISTRY_URL }}:arm64 --file oauth2-mock/Dockerfile oauth2-mock
      - name: Build latest manifest
        shell: bash
        run: |
          docker manifest create ${{ env.REGISTRY_URL }}:latest \
          ${{ env.REGISTRY_URL }}:amd64 ${{ env.REGISTRY_URL }}:arm64
      - name: Push latest manifest
        shell: bash
        run: |
          docker manifest push ${{ env.REGISTRY_URL }}:latest
