name: gRPC load testing image build & push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: europe-central2-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.DOCKER_PUSH_SA_KEY }}
      - name: Copy hello.proto into grpc-loadtest
        run: cp grpcbin/pkg/hello/hello.proto grpc-loadtest/hello.proto
        shell: bash
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: grpc-loadtest/Dockerfile
          context: grpc-loadtest
          push: true
          tags: europe-central2-docker.pkg.dev/sap-se-cx-kyma-goat/networking-dev-tools/grpc-loadtest:${{ github.sha }},europe-central2-docker.pkg.dev/sap-se-cx-kyma-goat/networking-dev-tools/grpc-loadtest:latest
