name: OAuth2 Mock image build & push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: europe-central2-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.DOCKER_PUSH_SA_KEY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: oauth2-mock/Dockerfile
          context: oauth2-mock
          push: true
          tags: europe-central2-docker.pkg.dev/sap-se-cx-kyma-goat/networking-dev-tools/oauth2-mock:${{ github.sha }},europe-central2-docker.pkg.dev/sap-se-cx-kyma-goat/networking-dev-tools/oauth2-mock:latest
